#!/usr/bin/env -S uv run python
# /// script
# dependencies = []
# ///
"""Read data/eventos_2018_2026.csv and emit app/lib/events.ts.

Run: `uv run scripts/build_events.py` from the repo root.
"""
from __future__ import annotations

import csv
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CSV_PATH = ROOT / "data" / "eventos_2018_2026.csv"
OUT_PATH = ROOT / "app" / "lib" / "events.ts"


def kind_for(category: str, name: str) -> str:
    cat = category.lower()
    low = name.lower()
    if "elecci" in cat or "comici" in cat or "elecc" in low:
        return "election"
    if any(k in cat for k in ("corrup", "escánd", "escand", "crisis", "catástr", "catastr", "pandemi")):
        return "crisis"
    if any(k in cat for k in ("institucional", "gobern", "política", "politica", "economía", "economia")):
        return "policy"
    return "moment"


def short_label(name: str, limit: int = 28) -> str:
    # Prefer to cut at a sensible boundary (· en · de · -)
    if len(name) <= limit:
        return name
    head = name[:limit]
    # truncate at last space inside the window
    cut = head.rfind(" ")
    if cut >= limit * 0.6:
        head = head[:cut]
    return head.rstrip(" ,-·") + "…"


IMPACT_PART = re.compile(r"([^;]+?)\s*\(([+\-0])\)")


def parse_impacts(raw: str) -> list[dict]:
    out: list[dict] = []
    for m in IMPACT_PART.finditer(raw or ""):
        party = m.group(1).strip().strip(";").strip()
        direction = m.group(2)
        if party:
            out.append({"party": party, "direction": direction})
    return out


def parse_parties(raw: str) -> list[str]:
    if not raw:
        return []
    return [p.strip() for p in raw.split(",") if p.strip()]


def parse_sources(raw: str) -> list[str]:
    if not raw:
        return []
    return [s.strip() for s in raw.split("|") if s.strip().startswith("http")]


def build_tags(row: dict) -> list[str]:
    tags: list[str] = []
    cat = row["categoria"].lower()
    if "corrup" in cat or "escánd" in cat or "escand" in cat:
        tags.append("corrupción")
    if "pandemi" in cat or "covid" in row["descripcion"].lower():
        tags.append("pandemia")
    if "elecc" in cat or "comici" in cat:
        tags.append("elecciones")
    if "económ" in cat or "econom" in cat:
        tags.append("economía")
    if "catástr" in cat or "catastr" in cat:
        tags.append("catástrofe")
    # Add top affected parties as tags
    for p in parse_parties(row["partidos_afectados"])[:3]:
        tags.append(p.lower().replace(" ", "-"))
    # dedupe preserving order
    seen: set[str] = set()
    dedup: list[str] = []
    for tag in tags:
        if tag and tag not in seen:
            dedup.append(tag)
            seen.add(tag)
    return dedup


def main() -> None:
    events = []
    with CSV_PATH.open(encoding="utf-8-sig") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            name = row["nombre_evento"].strip()
            category = row["categoria"].strip()
            events.append({
                "id": row["id_evento"].strip(),
                "date": row["fecha_evento"].strip(),
                "kind": kind_for(category, name),
                "category": category,
                "ambito": row["ambito"].strip(),
                "mechanism": row["mecanismo_dominante"].strip(),
                "label": short_label(name),
                "headline": name,
                "body": row["descripcion"].strip(),
                "explanation": row["explicacion_impacto"].strip(),
                "affected": parse_parties(row["partidos_afectados"]),
                "impacts": parse_impacts(row["impacto_probable"]),
                "relevance": int(row["relevancia_1_5"].strip()),
                "confidence": row["confianza_analitica"].strip(),
                "sources": parse_sources(row["fuentes"]),
                "tags": build_tags(row),
            })
    events.sort(key=lambda e: e["date"])

    payload = json.dumps(events, ensure_ascii=False, indent=2)

    OUT_PATH.write_text(
        "// AUTO-GENERATED by scripts/build_events.py — do not edit by hand.\n"
        "// Source: data/eventos_2018_2026.csv\n\n"
        "export type EventKind = \"election\" | \"crisis\" | \"policy\" | \"moment\";\n"
        "\n"
        "export type EventImpact = {\n"
        "  party: string;\n"
        "  direction: \"+\" | \"-\" | \"0\";\n"
        "};\n"
        "\n"
        "export type PoliticalEvent = {\n"
        "  id: string;\n"
        "  date: string;          // YYYY-MM-DD\n"
        "  kind: EventKind;\n"
        "  category: string;\n"
        "  ambito: string;\n"
        "  mechanism: string;\n"
        "  label: string;         // short (<=28 chars) for chart annotations\n"
        "  headline: string;      // full event name\n"
        "  body: string;          // neutral description\n"
        "  explanation: string;   // why it mattered for polling\n"
        "  affected: string[];\n"
        "  impacts: EventImpact[];\n"
        "  relevance: number;     // 1..5\n"
        "  confidence: \"Alta\" | \"Media\" | \"Baja\" | string;\n"
        "  sources: string[];\n"
        "  tags: string[];\n"
        "};\n"
        "\n"
        f"export const POLITICAL_EVENTS: PoliticalEvent[] = {payload};\n"
        "\n"
        "export const EVENT_KIND_LABEL: Record<EventKind | \"all\", string> = {\n"
        "  all: \"todos\",\n"
        "  election: \"elecciones\",\n"
        "  crisis: \"crisis\",\n"
        "  policy: \"política\",\n"
        "  moment: \"momento\",\n"
        "};\n"
        "\n"
        "export const EVENT_CATEGORIES: string[] = Array.from(\n"
        "  new Set(POLITICAL_EVENTS.map((e) => e.category)),\n"
        ").sort();\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT_PATH.relative_to(ROOT)} · {len(events)} events")


if __name__ == "__main__":
    main()
